POST http://0.0.0.0:8000/api/v1/auth/register
content-type: application/json

{
    "name": "atom",
    "email": "atomic@email.com",
    "password": "atomic123",
    "address_line": "atomic street",
    "city": "atomic city",
    "province": "atomic province",
    "postal_code": "atomic postal code",
    "country": "atomic country"
}
